import type {Metadata} from "next";
import "@/app/_styles/globals.css";
import { inter } from '@/app/_components/fonts';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                      children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body suppressContentEditableWarning={true}
                  className={`${inter.className} antialiased`}
            >
                {/*Tailwind antialiased class which smooths out the font.*/}
                {children}
            </body>
        </html>
    );
}
